# Generated by Django 5.2.4 on 2025-07-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_librarian_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
            preserve_default=False,
        ),
    ]
