# Generated by Django 5.2.4 on 2025-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_exam_course_exam_department_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
