# Generated by Django 5.2.4 on 2025-07-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feepayment_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
    ]
