# Generated by Django 5.2.4 on 2025-07-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attendance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
