# Generated by Django 5.2.4 on 2025-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('hod', 'HOD'), ('faculty', 'Faculty'), ('student', 'Student'), ('parent', 'Parent'), ('librarian', 'Librarian'), ('accountant', 'Accountant'), ('transport', 'Transport Staff'), ('hostel', 'Hostel Incharge')], max_length=30),
        ),
    ]
