# Generated by Django 5.2.4 on 2025-07-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='core.student'),
        ),
    ]
