# Generated by Django 5.2.4 on 2025-07-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_attendance_department_remove_attendance_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
