# Generated by Django 5.2.4 on 2025-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_revenue_studnts_subjectresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
