# Generated by Django 5.2.4 on 2025-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
