# Generated by Django 5.2.4 on 2025-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_attendance_section_attendance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
