# Generated by Django 5.2.4 on 2025-07-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_exam_section_feestructure_section_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubjectmapping',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
