# Generated by Django 5.2.4 on 2025-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_exam_section_feestructure_section_student_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='section',
            field=models.CharField(max_length=5),
        ),
    ]
