# Generated by Django 5.2.4 on 2025-07-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_timetableentry_section'),
        ('core', '0023_attendance_status'),
    ]

    operations = [
    ]
