# Generated by Django 5.2.4 on 2025-07-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_attendance_status_remove_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='exam',
        ),
        migrations.AddField(
            model_name='mark',
            name='credits',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Average'), ('C', 'Pass'), ('F', 'Fail')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='marks',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.student'),
        ),
        migrations.DeleteModel(
            name='Studnts',
        ),
        migrations.DeleteModel(
            name='SubjectResult',
        ),
    ]
