# Generated by Django 5.2.4 on 2025-07-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_subjectresult_student_remove_mark_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
    ]
