# Generated by Django 5.2.4 on 2025-07-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_mark_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
            preserve_default=False,
        ),
    ]
