# Generated by Django 5.2.4 on 2025-07-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_feestructure_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='Student',
        ),
    ]
