# Generated by Django 5.2.4 on 2025-07-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
    ]
