# Generated by Django 5.2.4 on 2025-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_coursematerial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
