# Generated by Django 5.2.4 on 2025-07-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_coursematerial_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='year',
        ),
    ]
