# Generated by Django 5.2.4 on 2025-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_coursematerial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='section',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
