# Generated by Django 5.2.4 on 2025-07-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_coursematerial_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='section',
        ),
    ]
