# Generated by Django 5.2.4 on 2025-07-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_coursematerial_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
