# Generated by Django 5.2.4 on 2025-07-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_subject_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
