from django.contrib import admin
from .models import *

admin.site.register(Role)
admin.site.register(User)
admin.site.register(Notice)
admin.site.register(ClassSection)
admin.site.register(Student)
admin.site.register(Parent)
admin.site.register(FacultyProfile)
admin.site.register(Leave)
admin.site.register(Course)
admin.site.register(Subject)
admin.site.register(FacultySubject)
admin.site.register(Timetable)
admin.site.register(Attendance)
admin.site.register(FeeStructure)
admin.site.register(FeePayment)
admin.site.register(Exam)
admin.site.register(Mark)
admin.site.register(Book)
admin.site.register(BookIssue)
admin.site.register(Vehicle)
admin.site.register(TransportAssignment)
admin.site.register(HostelRoom)
admin.site.register(HostelAssignment)