from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.login_view, name='login'),
    path('', views.logout_view, name='logout'),

    path('dashboard/', views.redirect_dashboard, name='redirect_dashboard'),
    path('dashboard/superadmin/', views.dashboard_superadmin, name='dashboard_superadmin'),
    path('dashboard/hod/', views.dashboard_hod, name='dashboard_hod'),
    path('dashboard/faculty/', views.dashboard_faculty, name='dashboard_faculty'),
    path('dashboard/hostel/', views.dashboard_hostel, name='hostel_dashboard'),
    path('dashboard/student/', views.dashboard_student, name='dashboard_student'),
    path('dashboard/parent/', views.dashboard_parent, name='dashboard_parent'),
    path('dashboard/librarian/', views.dashboard_librarian, name='dashboard_librarian'),
    path('dashboard/accountant/', views.dashboard_accountant, name='dashboard_accountant'),
    path('dashboard/transport/', views.dashboard_transport, name='dashboard_transport'),
    path('students/', views.student_list, name='student_list'),
    path('student/attendance/', views.student_attendance_view, name='student_attendance'),
    path('student/fee/', views.student_fee, name='student_fee'),
    path('student/marks/', views.student_marks, name='student_marks'),
    path('student/timetable/', views.student_timetable, name='student_timetable'),
    path('students/add/', views.student_add, name='student_add'),
    path('students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('students/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('students/<int:pk>/promote/', views.promote_student, name='student_promote'),
    path('students/<int:pk>/idcard/', views.student_idcard, name='student_idcard'),
    path('faculty/', views.faculty_list, name='faculty_list'),
    path('faculty/add/', views.faculty_add, name='faculty_add'),
    path('faculty/<int:pk>/edit/', views.faculty_edit, name='faculty_edit'),
    path('faculty/<int:pk>/delete/', views.faculty_delete, name='faculty_delete'),
    path('faculty/leaves/', views.faculty_leave_list, name='faculty_leave_list'),
    path('faculty/leave/apply/', views.faculty_leave_apply, name='faculty_leave_apply'),
    path('leaves/<int:pk>/approve/', views.leave_approve, name='leave_approve'),
    path('leaves/<int:pk>/reject/', views.leave_reject, name='leave_reject'),
    path('faculty/subjects/', views.subject_mapping_list, name='subject_mapping_list'),
    path('faculty/subjects/add/', views.subject_mapping_add, name='subject_mapping_add'),
    path('timetable/', views.timetable_list, name='timetable_list'),
    path('timetable/add/', views.timetable_add, name='timetable_add'),
    path('timetable/faculty/', views.faculty_timetable_view, name='faculty_timetable'),
    path('timetable/print/', views.timetable_print, name='timetable_print'),
    path('attendance/mark/', views.mark_attendance, name='mark_attendance'),
    path('attendance/view/', views.view_attendance, name='view_attendance'),

   # path('attendance/submit/', views.submit_attendance, name='submit_attendance'),
    path('fee/structure/', views.fee_structure_list, name='fee_structure_list'),
    path('fee/structure/add/', views.fee_structure_add, name='fee_structure_add'),
    path('fee/structure/edit/<int:pk>/', views.fee_structure_edit, name='fee_structure_edit'),
    path('fee/structure/delete/<int:pk>/', views.fee_structure_delete, name='fee_structure_delete'),
    path('fee/receipt/<int:payment_id>/', views.generate_fee_receipt_pdf, name='generate_fee_receipt_pdf'),
    path('fee/payment/', views.fee_payment_list, name='fee_payment_list'),
    path('fee/payment/add/', views.fee_payment_add, name='fee_payment_add'),
    path('exams/', views.exam_list, name='exam_list'),
    path('exams/add/', views.exam_add, name='exam_add'),
    path('marks/<int:exam_id>/', views.mark_entry, name='mark_entry'),
    path('results/<int:student_id>/', views.view_result, name='view_result'),
    path('library/books/', views.book_list, name='book_list'),
    path('library/books/add/', views.book_add, name='book_add'),
    path('library/issues/', views.issue_list, name='issue_list'),
    path('library/issues/add/', views.issue_book, name='issue_book'),
    path('library/issues/return/<int:pk>/', views.return_book, name='return_book'),   
    path('transport/vehicles/', views.vehicle_list, name='vehicle_list'),
    path('transport/vehicles/add/', views.vehicle_add, name='vehicle_add'),
    path('transport/assign/', views.assign_transport, name='assign_transport'),
    path('hostel/list/', views.hostel_list, name='hostel_list'),
    path('hostel/add/', views.hostel_add, name='hostel_add'),
    path('hostel/rooms/', views.room_list, name='hostel_room_list'),
    path('hostel/rooms/add/', views.room_add, name='room_add'),
    path('hostel/allocate/', views.allocate_hostel, name='allocate_hostel'),
    path('notices/', views.notice_list, name='notice_list'),
    path('notices/create/', views.create_notice, name='create_notice'),
    path('messages/', views.message_list, name='message_list'),
    path('messages/send/', views.send_message, name='send_message'),
   # path('reports/attendance/', views.attendance_report, name='attendance_report'),
    path('reports/fee/', views.fee_report, name='fee_report'),
    path('reports/top/', views.top_performers, name='top_performers'),
    path('reports/export-fee/', views.export_fee_csv, name='export_fee_csv'),
    path('transport/allocations/', views.allocation_list, name='allocation_list'),
    path('transport/allocations/add/', views.allocation_add, name='allocation_add'),
    path('transport/allocations/<int:pk>/edit/', views.allocation_edit, name='allocation_edit'),
    path('transport/allocations/<int:pk>/delete/', views.allocation_delete, name='allocation_delete'),
    path('transport/allocations/<int:pk>/toggle-paid/', views.allocation_toggle_paid, name='allocation_toggle_paid'),
    path('student/timetable/download/', views.student_timetable_pdf, name='student_timetable_pdf'),
    path('faculty/attendance/', views.mark_faculty_attendance, name='mark_faculty_attendance'),
    path('faculty/attendance/report/', views.faculty_attendance_report, name='faculty_attendance_report'),
    #path('api/departments/', views.get_departments, name='get_departments'),
    #path('api/subjects/', views.get_subjects, name='get_subjects'),
    #path('api/students/', views.get_students_by_subject, name='get_students_by_subject'),
    #path('attendance/mark/', views.mark_attendance, name='submit_attendance'),
    #path('api/student-list/', views.student_list_api, name='student_list_api'),
    path('reports/gpa/', views.gpa_report_view, name='gpa_report'),
    path('gpa-graph/', views.gpa_graph_view, name='gpa_graph'),
    path('revenue-report/', views.revenue_report_view, name='revenue_report'),
    path('attendance/mark/', views.mark_attendance, name='mark_attendance'),
    path('attendance/view/', views.view_attendance, name='view_attendance'),
    path('api/students/', views.get_students_by_class, name='get_students_by_class'),
    path('attendance/report/', views.attendance_report, name='attendance_report'),
    path("gpa-graph-page/", views.gpa_graph_view, name="gpa_graph_page"),
    path('reports/gpa-graph/', views.gpa_graph_page_view, name='gpa_graph')



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
